### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by ghost** [crust87/Android-FFmpegExecutor#1]
Hi, yo have the script to compile ffmpeg? Because I'm trying to put rtmpdump to ffmpeg. Can you provide me help please?

**Comment by crust87** [comment]
Sorry, I did't compile my binary and forgot where i get
I will comment again if i find repository i get ffmpeg binary.
i think that repository has script

**Comment by crust87** [comment]
oh.. i think i have got my binary at "https://github.com/WritingMinds/ffmpeg-android-java"
you already know..

**Comment by ghost** [comment]
Thanks! Maybe soon make you a pull request with some improvement :)

**Comment by crust87** [comment]
i really wish. haha
